name = "lore-md"
main = "src/worker.js"
compatibility_date = "2025-12-04"
account_id = "de09342a728de2c25c85cc6b34d68739"
workers_dev = true

[durable_objects]
bindings = [
  { name = "DOMAIN_DO", class_name = "DomainDO" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["DomainDO"]
